os: linux
dist: focal
language: minimal

env:
  - FPGA_FAM="xc7"
  - FPGA_FAM="eos-s3"

before_install:
  - sudo apt update -y
  - sudo apt install -y python3-pip python3-setuptools git
  - sudo pip3 install dataclasses
  - sudo pip3 install git+https://github.com/antmicro/tuttest

script:
  - scripts/ci/install-toolchain.sh $FPGA_FAM
  - scripts/ci/build.sh $FPGA_FAM
