os: linux
dist: focal
language: minimal

services:
  - docker

env:
  # Testing QuickLogic toolchain on all OSes
  - TOOLCHAIN=quicklogic      OS=ubuntu OS_VERSION=trusty
  - TOOLCHAIN=quicklogic      OS=ubuntu OS_VERSION=xenial
  - TOOLCHAIN=quicklogic      OS=ubuntu OS_VERSION=bionic
  - TOOLCHAIN=quicklogic      OS=ubuntu OS_VERSION=eoan
  - TOOLCHAIN=quicklogic      OS=ubuntu OS_VERSION=focal
  - TOOLCHAIN=quicklogic      OS=centos OS_VERSION=6
  - TOOLCHAIN=quicklogic      OS=centos OS_VERSION=7
  - TOOLCHAIN=quicklogic      OS=centos OS_VERSION=8
  # Testing Xilinx 7 Series toolchain on all OSes
  - TOOLCHAIN=xilinx-series-7 OS=ubuntu OS_VERSION=trusty
  - TOOLCHAIN=xilinx-series-7 OS=ubuntu OS_VERSION=xenial
  - TOOLCHAIN=xilinx-series-7 OS=ubuntu OS_VERSION=bionic
  - TOOLCHAIN=xilinx-series-7 OS=ubuntu OS_VERSION=eoan
  - TOOLCHAIN=xilinx-series-7 OS=ubuntu OS_VERSION=focal
  - TOOLCHAIN=xilinx-series-7 OS=centos OS_VERSION=6
  - TOOLCHAIN=xilinx-series-7 OS=centos OS_VERSION=7
  - TOOLCHAIN=xilinx-series-7 OS=centos OS_VERSION=8

before_install:
        - sudo locale-gen "en_US.UTF-8"
        - export LANG="en_US.UTF-8"
        - source .github/travis/common.sh
        - rm README.rst && make README.rst && .github/travis/git-check.sh
        - pip install git+https://github.com/antmicro/tuttest@prefix-lines-with#egg=tuttest

install:
 - if [ "$OS" = "ubuntu" ]; then export INSTALL_COMMAND="apt update && apt install -y"; fi
 - if [ "$OS" = "centos" ]; then export INSTALL_COMMAND="yum -y install"; fi
 - if [ "$OS" = "ubuntu" ]; then export INSTALL_PACKAGES="git wget make"; fi
 - if [ "$OS" = "centos" ]; then export INSTALL_PACKAGES="git wget make"; fi
 - export DOCKER_NAME=test
 - export IN_DOCKER_EXEC="docker exec -t $DOCKER_NAME bash -c"
 - docker create
        --name $DOCKER_NAME
        --env LANG="en_US.UTF-8"
        --env LANGUAGE="en_US"
        --env DEBIAN_FRONTEND="noninteractive"
        -v /home/travis:/home/travis
        --workdir $PWD
        --tty
        $OS:$OS_VERSION
 - docker start $DOCKER_NAME
 - $IN_DOCKER_EXEC "$INSTALL_COMMAND $INSTALL_PACKAGES"
 - tuttest README.rst unnamed0 --prefix-lines-with "$IN_DOCKER_EXEC" | bash -
 - if [ "$TOOLCHAIN" = "xilinx-series-7" ]; then tuttest xc7/README.rst unnamed0 --prefix-lines-with "$IN_DOCKER_EXEC" | bash -; fi
 - if [ "$TOOLCHAIN" = "quicklogic" ];      then tuttest eos-s3/README.rst unnamed0 --prefix-lines-with "$IN_DOCKER_EXEC" | bash -; fi

script:
 - if [ "$TOOLCHAIN" = "xilinx-series-7" ]; then tuttest xc7/README.rst unnamed1,unnamed2,unnamed3,unnamed4,unnamed5 --prefix-lines-with "$IN_DOCKER_EXEC" | bash -; fi
 - if [ "$TOOLCHAIN" = "quicklogic" ];      then tuttest eos-s3/README.rst unnamed1,unnamed2 --prefix-lines-with "$IN_DOCKER_EXEC" | bash -; fi

