name: tuttest
on: [push, pull_request]

jobs:
  examples:
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - {toolchain: "eos-s3", os: "ubuntu", os-version: "xenial", example: "eos-s3-counter"}
          - {toolchain: "eos-s3", os: "ubuntu", os-version: "bionic", example: "eos-s3-counter"}
          - {toolchain: "eos-s3", os: "ubuntu", os-version: "eoan",   example: "eos-s3-counter"}
          - {toolchain: "eos-s3", os: "ubuntu", os-version: "focal",  example: "eos-s3-counter"}
          - {toolchain: "eos-s3", os: "centos", os-version: "7",      example: "eos-s3-counter"}
          - {toolchain: "eos-s3", os: "centos", os-version: "8",      example: "eos-s3-counter"}

          - {toolchain: "xc7",    os: "ubuntu", os-version: "xenial", example: "xc7-counter"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "bionic", example: "xc7-counter"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "eoan",   example: "xc7-counter"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "focal",  example: "xc7-counter"}
          - {toolchain: "xc7",    os: "centos", os-version: "7",      example: "xc7-counter"}
          - {toolchain: "xc7",    os: "centos", os-version: "8",      example: "xc7-counter"}

          - {toolchain: "xc7",    os: "ubuntu", os-version: "xenial", example: "xc7-picosoc"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "bionic", example: "xc7-picosoc"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "eoan",   example: "xc7-picosoc"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "focal",  example: "xc7-picosoc"}
          - {toolchain: "xc7",    os: "centos", os-version: "7",      example: "xc7-picosoc"}
          - {toolchain: "xc7",    os: "centos", os-version: "8",      example: "xc7-picosoc"}

          - {toolchain: "xc7",    os: "ubuntu", os-version: "xenial", example: "xc7-litex"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "bionic", example: "xc7-litex"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "eoan",   example: "xc7-litex"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "focal",  example: "xc7-litex"}
          - {toolchain: "xc7",    os: "centos", os-version: "7",      example: "xc7-litex"}
          - {toolchain: "xc7",    os: "centos", os-version: "8",      example: "xc7-litex"}

          - {toolchain: "xc7",    os: "ubuntu", os-version: "xenial", example: "xc7-linux"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "bionic", example: "xc7-linux"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "eoan",   example: "xc7-linux"}
          - {toolchain: "xc7",    os: "ubuntu", os-version: "focal",  example: "xc7-linux"}
          - {toolchain: "xc7",    os: "centos", os-version: "7",      example: "xc7-linux"}
          - {toolchain: "xc7",    os: "centos", os-version: "8",      example: "xc7-linux"}

    env:
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US"
      INSTALL_DIR: "/root/opt/symbiflow"
      DEBIAN_FRONTEND: "noninteractive"

    steps:
    - name: Prepare Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      if: ${{matrix.os == "ubuntu"}}
      run: |
        apt -qqy update && apt install git python3 python3-pip

    - name: Set Up Python
      if: ${{matrix.os == "centos" && matrix.os-version == "7"}}
      run: |
        yum -y install centos-release-scl
        yum -y install rh-python36
        cp /opt/rh/rh-python36/root/usr/bin/* /usr/bin

    - name: Set Up Python
      if: ${{matrix.os == "centos" && matrix.os-version == "8"}}
      run: |
        yum -y install python3

    - name: Install Prerequisites
      run: |
        pip3 install git+https://github.com/antmicro/tuttest#egg=tuttest dataclasses

    - name: Test Main README.rst
      run: |
        rm README.rst && make README.rst && .github/scripts/git-check.sh

    - name: (tuttest) Install SymbiFlow Toolchain
      run: |
        source .github/scripts/tuttest_exec.sh
        tuttest_exec README.rst install-req-${{matrix.os}}
        tuttest_exec README.rst wget-conda
        tuttest_exec ${{matrix.toolchain}}/README.rst ${{matrix.toolchain}}-setup-toolchain

    - name: (tuttest) Test Example
      run: |
        source .github/scripts/tuttest_exec.sh
        tuttest_exec ${{matrix.toolchain}}/README.rst ${{matrix.toolchain}}-prepare-env,${{matrix.example}}

    - uses: actions/upload-artifact@v2
      with:
        path: |
          **/*.bit
          !xc7/litex_demo/pythondata-cpu-microwatt/**/*.bit
